name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/01-ssh-bruteforce-detector
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r 01-ssh-bruteforce-detector/requirements.txt

      - name: Run tests
        run: |
          python -m pytest -q 01-ssh-bruteforce-detector/tests
