name: CI
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    # Make every step run from the detector folder
    defaults:
      run:
        working-directory: 01-ssh-bruteforce-detector

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        # Make sure Python can import the 'src' package
        env:
          PYTHONPATH: ${{ github.workspace }}/01-ssh-bruteforce-detector
        run: python -m pytest -q tests
