name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ripmime whois curl jq dnsutils openssl whatweb
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Add requirements.txt if you have Python dependencies
        # pip install -r requirements.txt
    
    - name: Run tests
      run: |
        # Add your test commands here
        ./phishing_ioc_collector.sh --help || echo "Script help test"
