name: CI

on:
  [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r 01-ssh-bruteforce-detector/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: 01-ssh-bruteforce-detector
        run: |
          cd 01-ssh-bruteforce-detector
          pytest -q
